### Getting Logs
GET http://localhost:5000/api/v1/logs/

### Creating a Log
POST http://localhost:5000/api/v1/logs/
Content-Type: application/json

{
    "desc": "Sample API Test",
    "startTime": "2022-03-23T04:43:41.887Z",
    "endTime": "2022-03-23T04:43:41.887Z"
}